version: '3.5'
services:
  api:
    image: wg-api:dev
    build: ./api/
    user: node
    working_dir: /home/node/app
    command: nodemon
    environment:
      WG_NAME: hc0
      WG_IP: 10.99.0.1
      WG_POOL: 10.99.0.0/16
      WG_PORT: 53
      WG_ENDPOINT: wg.hcpss.org
    ports:
      - target: 9000
        published: 9000
        mode: host
    secrets:
      - wg_api_key
      - wg_client_api_key
    volumes:
      - type: bind
        source: ./api
        target: /home/node/app
      - type: volume
        source: data
        target: /data
volumes:
  data: {}
secrets:
  wg_api_key:
    external: true
  wg_client_api_key:
    external: true
