version: '3.5'
services:
  api:
    image: nickadam/ordig:1.0
    build: ./api/
    user: node
    working_dir: /home/node/app
    command: bash -c 'while true; do npm start; done'
    environment:
      WG_NAME: wg0
      WG_IP: 10.99.0.1
      WG_POOL: 10.99.0.0/16
      WG_NAMESPACE: example.local
      WG_NAMESERVER: 10.10.10.10
      WG_PORT: 51820
      WG_ENDPOINT: ordig.example.com
      WG_SERVER_API_KEY: {{WG_SERVER_API_KEY}}
      WG_CLIENT_API_KEY: {{WG_CLIENT_API_KEY}}
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - type: bind
        source: ./api
        target: /home/node/app
      - type: volume
        source: data
        target: /data
volumes:
  data: {}
